<?php 
@session_start();
@$user=$_SESSION['user'];
@$password=$_SESSION['password'];
include_once("password.php");
$x="SELECT * FROM users  WHERE  name='$user' AND password='$password' ";
$x=mysqli_query($connect,$x)or die(mysqli_error($connect));
if(mysqli_num_rows($x)>0){}
else{$_SESSION['message']="ACCESS  DENIED"; header("LOCATION:accessdenied4.php");exit;}

?><!doctype html>
<html lang="us">
<head>
	<meta charset="utf-8">
	<title>jQuery UI Example Page</title>
	<link href="stylesheets/jquery-ui.css" rel="stylesheet">
	<link href="stylesheets/forms.css" rel="stylesheet">
			<link rel="stylesheet" type="text/css" href="stylesheets/dhtmlxcalendar.css"/>
	<script src="pluggins/dhtmlxcalendar.js"></script>
	<script src="pluggins/date.js"></script>
    <style type="text/css">
<!--
form{width:80%; margin-left:15%}
-->
.tbl_container{ overflow:auto; width: 100%; height:200px;border:thick; border:#0000FF; }
.select{ width:40%;}

.right{ width:50%; float:right;}
.left{width:50%; float:left;}
    </style>
		<SCRIPT type="text/javascript">

    window.history.forward();

    function noBack() { window.history.forward(); }

</SCRIPT>
</head>
<body  oncontextmenu="return false;"  onLoad="noBack();" >
	
    <div id="tabs">
	<ul>
		<li><a href="#tabs-1">DATES</a></li>
	</ul>
	<div id="tabs-1">
<form method="post"  action="dateset2.php"  id="dateset"><fieldset>
	  <p>
	  <div style="position:relative;height:10px;">
		From
&nbsp;&nbsp;&nbsp;
<input type="date"  name="date1"  id="date1"  required="on" >
		To
		<input type="date"   name="date2"  id="date2"  required="on">
	  </div>
	  <p><br>
	    From &nbsp;&nbsp;&nbsp;:<?php echo @$_SESSION['date1'];?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo @$_SESSION['date2'];?>	 </p><hr>
	  <p>
	Min
	  <label>
	<input type="text"  pattern="[0-9A-Za-z ]+"  title="ENTER CAPITAL ALPHA NUMERIC " name="min"   placeholder="Minimum"  size="20" class="input" value="<?php echo @$_SESSION['min'];?>"  required="on">
	</label>
	Max
	<label><input  type="text"  pattern="[0-9A-Za-z ]+"  title="ENTER CAPITAL ALPHA NUMERIC "  name="max"  placeholder="Maximum"  size="20"   class="input" value="<?php echo @$_SESSION['max'];?>"   required="on" >
	</label>
	<label></label>
	</p>
	  <p>
        <input name="Submit5" type="submit" class="button" value="FILTER">
        <input name="Submit23" type="reset" class="button" value="Reset">
      </p>
        <BR>
        </p></fieldset>
    </form>
	<form  action="accountsearch.php"  method="post"  id="accountsearch"><fieldset><legend>METER RANGE</legend>
		  <p>
	Min
	  <label>
	<input type="text"  pattern="[0-9A-Za-z ]+"  title="ENTER CAPITAL ALPHA NUMERIC "   name="min"  placeholder="Minimum"  size="20" class="input" value="<?php echo @$_SESSION['min2'];?>"  required="on">
	</label>
	Max
	<label><input   type="text"  pattern="[0-9A-Za-z ]+"  title="ENTER CAPITAL ALPHA NUMERIC "  name="max"  placeholder="Maximum"  size="20"   class="input" value="<?php echo @$_SESSION['max2'];?>"  required="on"  >
	</label>
	<label></label>
	</p>
	  <p>
        <input name="Submit5" type="submit" class="button" value="FILTER">
        <input name="Submit23" type="reset" class="button" value="Reset">
      </p>
        <BR>
        </p></fieldset>
	</form>
	<form   action="search.php" method="post"  id="search"><fieldset><legend>SEARCH</legend>
	<div class="left"><input name="accountsearch" type="text" placeholder="Meter Number"><br><br>
	<input name="name" type="text" placeholder="Account Name"><br><br><select name="accountstatus"  class="select" > <option value="">STATUS</option><option value="CONP">CONP</option><option value="NEW ACC">NEW ACC</option><option value="CONNECTED">CONNECTED</option><option value="COR">COR</option></select>
	</div><div class="right"><input name="account" type="text" placeholder="Account Number"><br><br><select name="accounttype"  class="select" > <option value="" >CLASS</option><option value="A" >CLASS A</option><option value="B" >CLASS B</option>  <option value="C" >CLASS C</option> <option value="D" >CLASS <option value="PRIVATE" >CLASS PRIVATE</option></option></select><br><br><input name="" type="submit"  class="button">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="" type="reset"  class="button">
	</div>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br><br></fieldset></form>
	</div>	
	</div>
<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
<h2 class="demoHeaders">
  <!-- Datepicker -->
</h2>
<h2 class="demoHeaders">
  <!-- Spinner -->
</h2>
<h2 class="demoHeaders">&nbsp;</h2>
<!-- Tooltip -->
<h2 class="demoHeaders">&nbsp;</h2>
<p id="tooltip">
  <!-- Highlight / Error -->
</p>
<script src="pluggins/jquery.js"></script>
<script src="pluggins/jquery-ui.js"></script>
<script type="text/javascript"> 
$(document).ready(function(){
var $rows = $('.table tr');
$('.searchtext').keyup(function() {
    var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();
    
    $rows.show().filter(function() {
        var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
        return !~text.indexOf(val);
    }).hide();
});
//////
$( "#tabs" ).tabs();
$("#dateset").submit(
function (){
var a=$("#date1").val();
if(a==""){alert("Invalid dates");return false;}
var b=$("#date2").val();
if(b==""){alert("Invalid dates");return false;}}
)
$("#accountsearch").submit(function(){
$.post("accountsearch.php",$("#accountsearch").serialize(),function(data){alert(data);});return false;
});

});</script>
</body>
</html>
