<?php 
@session_start();
$user=$_SESSION['user'];
$password=$_SESSION['password'];
$currentreading=$_POST['currentreading'];$currentreading2=$_POST['currentreading2'];
include_once("password.php");
@$date1=$_SESSION['date1'];@$date2=$_SESSION['date2'];$date=$_POST['date'];
$x="SELECT * FROM users  WHERE  name='$user' AND password='$password' AND  level >=1  AND  level ='ACTIVE'";
$x=mysqli_query($connect,$x)or die(mysqli_error($connect));
if(mysqli_num_rows($x)>0){}
else{include_once("accessdenied.php");exit;}
?>
<!doctype html>
<html lang="us">
<head>
	<meta charset="utf-8">
	<title>jQuery UI Example Page</title>
	<link href="stylesheets/jquery-ui.css" rel="stylesheet">
	<link href="stylesheets/forms.css" rel="stylesheet">
			<link rel="stylesheet" type="text/css" href="stylesheets/dhtmlxcalendar.css"/>
	<script src="pluggins/dhtmlxcalendar.js"></script>
	<script src="pluggins/date.js"></script>
    <style type="text/css">
<!--
form{width:65%; margin-left:15%}
-->
.tbl_container{ overflow:auto; width: 100%; height:200px;border:thick; border:#0000FF; }

    </style>
</head>
<body   onLoad="doOnLoad();" >
	
    <div id="tabs">
	<ul>
		<li><a href="#tabs-1">LOGIN</a></li>
	</ul>
	<div id="tabs-1">
<form  action="" method="post" id="logginform"> 

<hr align="center" />
<fieldset>
<legend></legend>
<h1>
  <p align="center"><strong>INVALID ENTRIES </strong></p>
</h1>
<p align="center">
</fieldset>

<hr align="center" />

</form>
	</div>	
	</div>
<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
<h2 class="demoHeaders">
  <!-- Datepicker -->
</h2>
<h2 class="demoHeaders">
  <!-- Spinner -->
</h2>
<h2 class="demoHeaders">&nbsp;</h2>
<!-- Tooltip -->
<h2 class="demoHeaders">&nbsp;</h2>
<p id="tooltip">
  <!-- Highlight / Error -->
</p>
<script src="pluggins/jquery.js"></script>
<script src="pluggins/jquery-ui.js"></script>
<script type="text/javascript"> 
$(document).ready(function(){
var $rows = $('.table tr');
$('.searchtext').keyup(function() {
    var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();
    
    $rows.show().filter(function() {
        var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
        return !~text.indexOf(val);
    }).hide();
});
//////
$( "#tabs" ).tabs();
$(".search").hide();
$(".tbl_container").show();

$(".umbutton").click( function () 
{
 $(".search").toggle();
 $(".tbl_container").toggle();
})
});</script>
</body>
</html>
