<?php 
session_start();
$user=$_SESSION['user'];
?>
<!doctype html>
<html lang="us">
<head>
	<meta charset="utf-8">
	<title>jQuery UI Example Page</title>
	<link href="stylesheets/jquery-ui.css" rel="stylesheet">
	<link href="stylesheets/form.css" rel="stylesheet">
	<link rel="stylesheet"   href="bootstrap/css/bootstrap.min.css" />
	<style>
	
	#idnumber-list{float:left;list-style:none;margin:0;padding:0;width:190px;}
#idnumber-list li{padding: 10px; background:#FAFAFA;border-bottom:#F0F0F0 1px solid;}
#idnumber-list li:hover{background:#F0F0F0;}
#search-box{padding: 10px;border: #F0F0F0 1px solid;} 


	@media print{ body{display:none; width:0%;} }
	</style>
	<script type="text/vbscript">
	function noBack() {window.history.forward();}	
	</script>
</head>
<body  oncontextmenu="return false;"  onLoad="noBack();">
<form action="exit.php" method="post" target="_parent"  onClick="noBack();"><input name="button3" type="submit" value="LOGOUT" class="btn-info btn-sm"   id="logout"/><br>
</form>

<div id="accordion">
  <h3><input type="button" value="FILTER"  class="btn-info btn-sm" >
  </h3>
  <div><a href="dateset.php" target="leftFrame">Filter set</a></div>
	<h3><input type="button" value="ADMIN"  class="btn-info btn-sm">
	</h3>
	<div class="links">
	<a href="users.php" target="leftFrame">Users</a><br>
  <a href="backuprestore.php" target="leftFrame">Backup</a></div>
	<h3>
	  <input name="button" type="button" value="REPORTS"  class="btn-info btn-sm" >
	</h3>
  <div><a href="reports.php" target="leftFrame">REPORTS</a><br><a href="balance.php" target="leftFrame">BALANCE</a>
 
  </div>
 <h3><input type="button" value="Billing"  class="btn-info btn-sm" >
  </h3>
  <div><a href="waterbill.php" target="leftFrame">Billing</a><br><a href="viewbill.php" target="leftFrame">Summary</a>
</div>
</div>

<form action="searchaccount.php" method="post" target="_parent"  id="searchaccount" >
 <div class="frmSearch">
<a href="#" title="INFO" data-toggle="popover" data-trigger="hover" data-content="Set  Account" data-placement="bottom"><input name="account" type="text" size="15" placeholder="Meter/Account No"  required="on"  class="form-control input-sm"   id="search-box"  autocomplete="off" ></a>
<div id="suggesstion-box"></div>
</div>
  <input  type="date"  name="date1"  required="on" class="form-control input-sm" value="<?php $yr= date("Y")-5; echo $yr.date("-m-d");?>" >
   <input  type="date"  name="date2"   required="on" class="form-control input-sm"  value="<?php echo date("Y-m-d");?>" >
  <input name="button3" type="submit" value="SEARCH"class="btn-info btn-sm"/>
  <label>
  <input name="Reset" type="reset"class="btn-info btn-sm" value="RESET">
  </label>
  <br>
</form>
</fieldset>
<!-- Autocomplete -->
<h2 class="demoHeaders">&nbsp;</h2>
<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
<h2 class="demoHeaders">
  <!-- Spinner -->
</h2>
<h2 class="demoHeaders">&nbsp;</h2>
<script src="pluggins/jquery.js"></script>
<script src="pluggins/jquery-ui.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript"> 
$(document).ready(function(){
$('[data-toggle="popover"]').popover(); 

$( "#accordion" ).accordion();
$("#searchaccount").submit(function(){
$.post("searchaccount.php",$("#searchaccount").serialize(),function (data){alert(data);})
return false;
})

});
</script>
<script>
$(document).ready(function(){
	$("#search-box").keyup(function(){
		$.ajax({
		type: "POST",
		url: "readCountry.php",
		data:'keyword='+$(this).val(),
		beforeSend: function(){
			$("#search-box").css("background","#FFF url(LoaderIcon.gif) no-repeat 165px");
		},
		success: function(data){
			$("#suggesstion-box").show();
			$("#suggesstion-box").html(data);
			$("#search-box").css("background","#FFF");
		}
		});
	});
});

function selectCountry(val) {
$("#search-box").val(val);
$("#suggesstion-box").hide();
}
</script>

</body>
</html>
